version: 2

sources:
  - name: bfsi
    description: BFSI OLAP database with fact and dimension tables
    database: bfsi_olap
    schema: main
    tables:
      - name: fact_transactions
        description: Transaction fact table
        columns:
          - name: transaction_key
            description: Primary key
          - name: transaction_amount
            description: Transaction amount
          - name: transaction_fee
            description: Transaction fee

      - name: fact_loans
        description: Loan fact table
        columns:
          - name: loan_key
            description: Primary key
          - name: loan_amount
            description: Loan amount
          - name: outstanding_balance
            description: Outstanding balance

      - name: dim_customer
        description: Customer dimension
        columns:
          - name: customer_key
            description: Primary key
          - name: customer_id
            description: Customer ID

      - name: dim_account
        description: Account dimension
        columns:
          - name: account_key
            description: Primary key
          - name: account_type
            description: Account type

      - name: dim_date
        description: Date dimension
        columns:
          - name: date_key
            description: Primary key
          - name: date
            description: Date value

      - name: dim_product
        description: Product dimension
        columns:
          - name: product_key
            description: Primary key
          - name: product_name
            description: Product name

      - name: dim_transaction_type
        description: Transaction type dimension
        columns:
          - name: transaction_type_key
            description: Primary key
          - name: transaction_type
            description: Transaction type
